
colour_maps = {
	{ guibg = 'snow', guibg_hex = '#fffafa', guifb = 'Black' },
	{ guibg = 'ghost white', guibg_hex = '#f8f8ff', guifb = 'Black' },
	{ guibg = 'ghostwhite', guibg_hex = '#f8f8ff', guifb = 'Black' },
	{ guibg = 'white smoke', guibg_hex = '#f5f5f5', guifb = 'Black' },
	{ guibg = 'whitesmoke', guibg_hex = '#f5f5f5', guifb = 'Black' },
	{ guibg = 'gainsboro', guibg_hex = '#dcdcdc', guifb = 'Black' },
	{ guibg = 'floral white', guibg_hex = '#fffaf0', guifb = 'Black' },
	{ guibg = 'floralwhite', guibg_hex = '#fffaf0', guifb = 'Black' },
	{ guibg = 'old lace', guibg_hex = '#fdf5e6', guifb = 'Black' },
	{ guibg = 'oldlace', guibg_hex = '#fdf5e6', guifb = 'Black' },
	{ guibg = 'linen', guibg_hex = '#faf0e6', guifb = 'Black' },
	{ guibg = 'antique white', guibg_hex = '#faebd7', guifb = 'Black' },
	{ guibg = 'antiquewhite', guibg_hex = '#faebd7', guifb = 'Black' },
	{ guibg = 'papaya whip', guibg_hex = '#ffefd5', guifb = 'Black' },
	{ guibg = 'papayawhip', guibg_hex = '#ffefd5', guifb = 'Black' },
	{ guibg = 'blanched almond', guibg_hex = '#ffebcd', guifb = 'Black' },
	{ guibg = 'blanchedalmond', guibg_hex = '#ffebcd', guifb = 'Black' },
	{ guibg = 'bisque', guibg_hex = '#ffe4c4', guifb = 'Black' },
	{ guibg = 'peach puff', guibg_hex = '#ffdab9', guifb = 'Black' },
	{ guibg = 'peachpuff', guibg_hex = '#ffdab9', guifb = 'Black' },
	{ guibg = 'navajo white', guibg_hex = '#ffdead', guifb = 'Black' },
	{ guibg = 'navajowhite', guibg_hex = '#ffdead', guifb = 'Black' },
	{ guibg = 'moccasin', guibg_hex = '#ffe4b5', guifb = 'Black' },
	{ guibg = 'cornsilk', guibg_hex = '#fff8dc', guifb = 'Black' },
	{ guibg = 'ivory', guibg_hex = '#fffff0', guifb = 'Black' },
	{ guibg = 'lemon chiffon', guibg_hex = '#fffacd', guifb = 'Black' },
	{ guibg = 'lemonchiffon', guibg_hex = '#fffacd', guifb = 'Black' },
	{ guibg = 'seashell', guibg_hex = '#fff5ee', guifb = 'Black' },
	{ guibg = 'honeydew', guibg_hex = '#f0fff0', guifb = 'Black' },
	{ guibg = 'mint cream', guibg_hex = '#f5fffa', guifb = 'Black' },
	{ guibg = 'mintcream', guibg_hex = '#f5fffa', guifb = 'Black' },
	{ guibg = 'azure', guibg_hex = '#f0ffff', guifb = 'Black' },
	{ guibg = 'alice blue', guibg_hex = '#f0f8ff', guifb = 'Black' },
	{ guibg = 'aliceblue', guibg_hex = '#f0f8ff', guifb = 'Black' },
	{ guibg = 'lavender', guibg_hex = '#e6e6fa', guifb = 'Black' },
	{ guibg = 'lavender blush', guibg_hex = '#fff0f5', guifb = 'Black' },
	{ guibg = 'lavenderblush', guibg_hex = '#fff0f5', guifb = 'Black' },
	{ guibg = 'misty rose', guibg_hex = '#ffe4e1', guifb = 'Black' },
	{ guibg = 'mistyrose', guibg_hex = '#ffe4e1', guifb = 'Black' },
	{ guibg = 'white', guibg_hex = '#ffffff', guifb = 'Black' },
	{ guibg = 'black', guibg_hex = '#000000', guifb = 'Black' },
	{ guibg = 'dark slate gray', guibg_hex = '#2f4f4f', guifb = 'Black' },
	{ guibg = 'darkslategray', guibg_hex = '#2f4f4f', guifb = 'Black' },
	{ guibg = 'dark slate grey', guibg_hex = '#2f4f4f', guifb = 'Black' },
	{ guibg = 'darkslategrey', guibg_hex = '#2f4f4f', guifb = 'Black' },
	{ guibg = 'dim gray', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'dimgray', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'dim grey', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'dimgrey', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'slate gray', guibg_hex = '#708090', guifb = 'Black' },
	{ guibg = 'slategray', guibg_hex = '#708090', guifb = 'Black' },
	{ guibg = 'slate grey', guibg_hex = '#708090', guifb = 'Black' },
	{ guibg = 'slategrey', guibg_hex = '#708090', guifb = 'Black' },
	{ guibg = 'light slate gray', guibg_hex = '#778899', guifb = 'Black' },
	{ guibg = 'lightslategray', guibg_hex = '#778899', guifb = 'Black' },
	{ guibg = 'light slate grey', guibg_hex = '#778899', guifb = 'Black' },
	{ guibg = 'lightslategrey', guibg_hex = '#778899', guifb = 'Black' },
	{ guibg = 'gray', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'grey', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'x11 gray', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'x11gray', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'x11 grey', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'x11grey', guibg_hex = '#bebebe', guifb = 'Black' },
	{ guibg = 'web gray', guibg_hex = '#808080', guifb = 'Black' },
	{ guibg = 'webgray', guibg_hex = '#808080', guifb = 'Black' },
	{ guibg = 'web grey', guibg_hex = '#808080', guifb = 'Black' },
	{ guibg = 'webgrey', guibg_hex = '#808080', guifb = 'Black' },
	{ guibg = 'light grey', guibg_hex = '#d3d3d3', guifb = 'Black' },
	{ guibg = 'lightgrey', guibg_hex = '#d3d3d3', guifb = 'Black' },
	{ guibg = 'light gray', guibg_hex = '#d3d3d3', guifb = 'Black' },
	{ guibg = 'lightgray', guibg_hex = '#d3d3d3', guifb = 'Black' },
	{ guibg = 'midnight blue', guibg_hex = '#191970', guifb = 'Black' },
	{ guibg = 'midnightblue', guibg_hex = '#191970', guifb = 'Black' },
	{ guibg = 'navy', guibg_hex = '#000080', guifb = 'Black' },
	{ guibg = 'navy blue', guibg_hex = '#000080', guifb = 'Black' },
	{ guibg = 'navyblue', guibg_hex = '#000080', guifb = 'Black' },
	{ guibg = 'cornflower blue', guibg_hex = '#6495ed', guifb = 'Black' },
	{ guibg = 'cornflowerblue', guibg_hex = '#6495ed', guifb = 'Black' },
	{ guibg = 'dark slate blue', guibg_hex = '#483d8b', guifb = 'Black' },
	{ guibg = 'darkslateblue', guibg_hex = '#483d8b', guifb = 'Black' },
	{ guibg = 'slate blue', guibg_hex = '#6a5acd', guifb = 'Black' },
	{ guibg = 'slateblue', guibg_hex = '#6a5acd', guifb = 'Black' },
	{ guibg = 'medium slate blue', guibg_hex = '#7b68ee', guifb = 'Black' },
	{ guibg = 'mediumslateblue', guibg_hex = '#7b68ee', guifb = 'Black' },
	{ guibg = 'light slate blue', guibg_hex = '#8470ff', guifb = 'Black' },
	{ guibg = 'lightslateblue', guibg_hex = '#8470ff', guifb = 'Black' },
	{ guibg = 'medium blue', guibg_hex = '#0000cd', guifb = 'Black' },
	{ guibg = 'mediumblue', guibg_hex = '#0000cd', guifb = 'Black' },
	{ guibg = 'royal blue', guibg_hex = '#4169e1', guifb = 'Black' },
	{ guibg = 'royalblue', guibg_hex = '#4169e1', guifb = 'Black' },
	{ guibg = 'blue', guibg_hex = '#0000ff', guifb = 'Black' },
	{ guibg = 'dodger blue', guibg_hex = '#1e90ff', guifb = 'Black' },
	{ guibg = 'dodgerblue', guibg_hex = '#1e90ff', guifb = 'Black' },
	{ guibg = 'deep sky blue', guibg_hex = '#00bfff', guifb = 'Black' },
	{ guibg = 'deepskyblue', guibg_hex = '#00bfff', guifb = 'Black' },
	{ guibg = 'sky blue', guibg_hex = '#87ceeb', guifb = 'Black' },
	{ guibg = 'skyblue', guibg_hex = '#87ceeb', guifb = 'Black' },
	{ guibg = 'light sky blue', guibg_hex = '#87cefa', guifb = 'Black' },
	{ guibg = 'lightskyblue', guibg_hex = '#87cefa', guifb = 'Black' },
	{ guibg = 'steel blue', guibg_hex = '#4682b4', guifb = 'Black' },
	{ guibg = 'steelblue', guibg_hex = '#4682b4', guifb = 'Black' },
	{ guibg = 'light steel blue', guibg_hex = '#b0c4de', guifb = 'Black' },
	{ guibg = 'lightsteelblue', guibg_hex = '#b0c4de', guifb = 'Black' },
	{ guibg = 'light blue', guibg_hex = '#add8e6', guifb = 'Black' },
	{ guibg = 'lightblue', guibg_hex = '#add8e6', guifb = 'Black' },
	{ guibg = 'powder blue', guibg_hex = '#b0e0e6', guifb = 'Black' },
	{ guibg = 'powderblue', guibg_hex = '#b0e0e6', guifb = 'Black' },
	{ guibg = 'pale turquoise', guibg_hex = '#afeeee', guifb = 'Black' },
	{ guibg = 'paleturquoise', guibg_hex = '#afeeee', guifb = 'Black' },
	{ guibg = 'dark turquoise', guibg_hex = '#00ced1', guifb = 'Black' },
	{ guibg = 'darkturquoise', guibg_hex = '#00ced1', guifb = 'Black' },
	{ guibg = 'medium turquoise', guibg_hex = '#48d1cc', guifb = 'Black' },
	{ guibg = 'mediumturquoise', guibg_hex = '#48d1cc', guifb = 'Black' },
	{ guibg = 'turquoise', guibg_hex = '#40e0d0', guifb = 'Black' },
	{ guibg = 'cyan', guibg_hex = '#00ffff', guifb = 'Black' },
	{ guibg = 'aqua', guibg_hex = '#00ffff', guifb = 'Black' },
	{ guibg = 'light cyan', guibg_hex = '#e0ffff', guifb = 'Black' },
	{ guibg = 'lightcyan', guibg_hex = '#e0ffff', guifb = 'Black' },
	{ guibg = 'cadet blue', guibg_hex = '#5f9ea0', guifb = 'Black' },
	{ guibg = 'cadetblue', guibg_hex = '#5f9ea0', guifb = 'Black' },
	{ guibg = 'medium aquamarine', guibg_hex = '#66cdaa', guifb = 'Black' },
	{ guibg = 'mediumaquamarine', guibg_hex = '#66cdaa', guifb = 'Black' },
	{ guibg = 'aquamarine', guibg_hex = '#7fffd4', guifb = 'Black' },
	{ guibg = 'dark green', guibg_hex = '#006400', guifb = 'Black' },
	{ guibg = 'darkgreen', guibg_hex = '#006400', guifb = 'Black' },
	{ guibg = 'dark olive green', guibg_hex = '#556b2f', guifb = 'Black' },
	{ guibg = 'darkolivegreen', guibg_hex = '#556b2f', guifb = 'Black' },
	{ guibg = 'dark sea green', guibg_hex = '#8fbc8f', guifb = 'Black' },
	{ guibg = 'darkseagreen', guibg_hex = '#8fbc8f', guifb = 'Black' },
	{ guibg = 'sea green', guibg_hex = '#2e8b57', guifb = 'Black' },
	{ guibg = 'seagreen', guibg_hex = '#2e8b57', guifb = 'Black' },
	{ guibg = 'medium sea green', guibg_hex = '#3cb371', guifb = 'Black' },
	{ guibg = 'mediumseagreen', guibg_hex = '#3cb371', guifb = 'Black' },
	{ guibg = 'light sea green', guibg_hex = '#20b2aa', guifb = 'Black' },
	{ guibg = 'lightseagreen', guibg_hex = '#20b2aa', guifb = 'Black' },
	{ guibg = 'pale green', guibg_hex = '#98fb98', guifb = 'Black' },
	{ guibg = 'palegreen', guibg_hex = '#98fb98', guifb = 'Black' },
	{ guibg = 'spring green', guibg_hex = '#00ff7f', guifb = 'Black' },
	{ guibg = 'springgreen', guibg_hex = '#00ff7f', guifb = 'Black' },
	{ guibg = 'lawn green', guibg_hex = '#7cfc00', guifb = 'Black' },
	{ guibg = 'lawngreen', guibg_hex = '#7cfc00', guifb = 'Black' },
	{ guibg = 'green', guibg_hex = '#00ff00', guifb = 'Black' },
	{ guibg = 'lime', guibg_hex = '#00ff00', guifb = 'Black' },
	{ guibg = 'x11 green', guibg_hex = '#00ff00', guifb = 'Black' },
	{ guibg = 'x11green', guibg_hex = '#00ff00', guifb = 'Black' },
	{ guibg = 'web green', guibg_hex = '#008000', guifb = 'Black' },
	{ guibg = 'webgreen', guibg_hex = '#008000', guifb = 'Black' },
	{ guibg = 'chartreuse', guibg_hex = '#7fff00', guifb = 'Black' },
	{ guibg = 'medium spring green', guibg_hex = '#00fa9a', guifb = 'Black' },
	{ guibg = 'mediumspringgreen', guibg_hex = '#00fa9a', guifb = 'Black' },
	{ guibg = 'green yellow', guibg_hex = '#adff2f', guifb = 'Black' },
	{ guibg = 'greenyellow', guibg_hex = '#adff2f', guifb = 'Black' },
	{ guibg = 'lime green', guibg_hex = '#32cd32', guifb = 'Black' },
	{ guibg = 'limegreen', guibg_hex = '#32cd32', guifb = 'Black' },
	{ guibg = 'yellow green', guibg_hex = '#9acd32', guifb = 'Black' },
	{ guibg = 'yellowgreen', guibg_hex = '#9acd32', guifb = 'Black' },
	{ guibg = 'forest green', guibg_hex = '#228b22', guifb = 'Black' },
	{ guibg = 'forestgreen', guibg_hex = '#228b22', guifb = 'Black' },
	{ guibg = 'olive drab', guibg_hex = '#6b8e23', guifb = 'Black' },
	{ guibg = 'olivedrab', guibg_hex = '#6b8e23', guifb = 'Black' },
	{ guibg = 'dark khaki', guibg_hex = '#bdb76b', guifb = 'Black' },
	{ guibg = 'darkkhaki', guibg_hex = '#bdb76b', guifb = 'Black' },
	{ guibg = 'khaki', guibg_hex = '#f0e68c', guifb = 'Black' },
	{ guibg = 'pale goldenrod', guibg_hex = '#eee8aa', guifb = 'Black' },
	{ guibg = 'palegoldenrod', guibg_hex = '#eee8aa', guifb = 'Black' },
	{ guibg = 'light goldenrod yellow', guibg_hex = '#fafad2', guifb = 'Black' },
	{ guibg = 'lightgoldenrodyellow', guibg_hex = '#fafad2', guifb = 'Black' },
	{ guibg = 'light yellow', guibg_hex = '#ffffe0', guifb = 'Black' },
	{ guibg = 'lightyellow', guibg_hex = '#ffffe0', guifb = 'Black' },
	{ guibg = 'yellow', guibg_hex = '#ffff00', guifb = 'Black' },
	{ guibg = 'gold', guibg_hex = '#ffd700', guifb = 'Black' },
	{ guibg = 'light goldenrod', guibg_hex = '#eedd82', guifb = 'Black' },
	{ guibg = 'lightgoldenrod', guibg_hex = '#eedd82', guifb = 'Black' },
	{ guibg = 'goldenrod', guibg_hex = '#daa520', guifb = 'Black' },
	{ guibg = 'dark goldenrod', guibg_hex = '#b8860b', guifb = 'Black' },
	{ guibg = 'darkgoldenrod', guibg_hex = '#b8860b', guifb = 'Black' },
	{ guibg = 'rosy brown', guibg_hex = '#bc8f8f', guifb = 'Black' },
	{ guibg = 'rosybrown', guibg_hex = '#bc8f8f', guifb = 'Black' },
	{ guibg = 'indian red', guibg_hex = '#cd5c5c', guifb = 'Black' },
	{ guibg = 'indianred', guibg_hex = '#cd5c5c', guifb = 'Black' },
	{ guibg = 'saddle brown', guibg_hex = '#8b4513', guifb = 'Black' },
	{ guibg = 'saddlebrown', guibg_hex = '#8b4513', guifb = 'Black' },
	{ guibg = 'sienna', guibg_hex = '#a0522d', guifb = 'Black' },
	{ guibg = 'peru', guibg_hex = '#cd853f', guifb = 'Black' },
	{ guibg = 'burlywood', guibg_hex = '#deb887', guifb = 'Black' },
	{ guibg = 'beige', guibg_hex = '#f5f5dc', guifb = 'Black' },
	{ guibg = 'wheat', guibg_hex = '#f5deb3', guifb = 'Black' },
	{ guibg = 'sandy brown', guibg_hex = '#f4a460', guifb = 'Black' },
	{ guibg = 'sandybrown', guibg_hex = '#f4a460', guifb = 'Black' },
	{ guibg = 'tan', guibg_hex = '#d2b48c', guifb = 'Black' },
	{ guibg = 'chocolate', guibg_hex = '#d2691e', guifb = 'Black' },
	{ guibg = 'firebrick', guibg_hex = '#b22222', guifb = 'Black' },
	{ guibg = 'brown', guibg_hex = '#a52a2a', guifb = 'Black' },
	{ guibg = 'dark salmon', guibg_hex = '#e9967a', guifb = 'Black' },
	{ guibg = 'darksalmon', guibg_hex = '#e9967a', guifb = 'Black' },
	{ guibg = 'salmon', guibg_hex = '#fa8072', guifb = 'Black' },
	{ guibg = 'light salmon', guibg_hex = '#ffa07a', guifb = 'Black' },
	{ guibg = 'lightsalmon', guibg_hex = '#ffa07a', guifb = 'Black' },
	{ guibg = 'orange', guibg_hex = '#ffa500', guifb = 'Black' },
	{ guibg = 'dark orange', guibg_hex = '#ff8c00', guifb = 'Black' },
	{ guibg = 'darkorange', guibg_hex = '#ff8c00', guifb = 'Black' },
	{ guibg = 'coral', guibg_hex = '#ff7f50', guifb = 'Black' },
	{ guibg = 'light coral', guibg_hex = '#f08080', guifb = 'Black' },
	{ guibg = 'lightcoral', guibg_hex = '#f08080', guifb = 'Black' },
	{ guibg = 'tomato', guibg_hex = '#ff6347', guifb = 'Black' },
	{ guibg = 'orange red', guibg_hex = '#ff4500', guifb = 'Black' },
	{ guibg = 'orangered', guibg_hex = '#ff4500', guifb = 'Black' },
	{ guibg = 'red', guibg_hex = '#ff0000', guifb = 'Black' },
	{ guibg = 'hot pink', guibg_hex = '#ff69b4', guifb = 'Black' },
	{ guibg = 'hotpink', guibg_hex = '#ff69b4', guifb = 'Black' },
	{ guibg = 'deep pink', guibg_hex = '#ff1493', guifb = 'Black' },
	{ guibg = 'deeppink', guibg_hex = '#ff1493', guifb = 'Black' },
	{ guibg = 'pink', guibg_hex = '#ffc0cb', guifb = 'Black' },
	{ guibg = 'light pink', guibg_hex = '#ffb6c1', guifb = 'Black' },
	{ guibg = 'lightpink', guibg_hex = '#ffb6c1', guifb = 'Black' },
	{ guibg = 'pale violet red', guibg_hex = '#db7093', guifb = 'Black' },
	{ guibg = 'palevioletred', guibg_hex = '#db7093', guifb = 'Black' },
	{ guibg = 'maroon', guibg_hex = '#b03060', guifb = 'Black' },
	{ guibg = 'x11 maroon', guibg_hex = '#b03060', guifb = 'Black' },
	{ guibg = 'x11maroon', guibg_hex = '#b03060', guifb = 'Black' },
	{ guibg = 'web maroon', guibg_hex = '#800000', guifb = 'Black' },
	{ guibg = 'webmaroon', guibg_hex = '#800000', guifb = 'Black' },
	{ guibg = 'medium violet red', guibg_hex = '#c71585', guifb = 'Black' },
	{ guibg = 'mediumvioletred', guibg_hex = '#c71585', guifb = 'Black' },
	{ guibg = 'violet red', guibg_hex = '#d02090', guifb = 'Black' },
	{ guibg = 'violetred', guibg_hex = '#d02090', guifb = 'Black' },
	{ guibg = 'magenta', guibg_hex = '#ff00ff', guifb = 'Black' },
	{ guibg = 'fuchsia', guibg_hex = '#ff00ff', guifb = 'Black' },
	{ guibg = 'violet', guibg_hex = '#ee82ee', guifb = 'Black' },
	{ guibg = 'plum', guibg_hex = '#dda0dd', guifb = 'Black' },
	{ guibg = 'orchid', guibg_hex = '#da70d6', guifb = 'Black' },
	{ guibg = 'medium orchid', guibg_hex = '#ba55d3', guifb = 'Black' },
	{ guibg = 'mediumorchid', guibg_hex = '#ba55d3', guifb = 'Black' },
	{ guibg = 'dark orchid', guibg_hex = '#9932cc', guifb = 'Black' },
	{ guibg = 'darkorchid', guibg_hex = '#9932cc', guifb = 'Black' },
	{ guibg = 'dark violet', guibg_hex = '#9400d3', guifb = 'Black' },
	{ guibg = 'darkviolet', guibg_hex = '#9400d3', guifb = 'Black' },
	{ guibg = 'blue violet', guibg_hex = '#8a2be2', guifb = 'Black' },
	{ guibg = 'blueviolet', guibg_hex = '#8a2be2', guifb = 'Black' },
	{ guibg = 'purple', guibg_hex = '#a020f0', guifb = 'Black' },
	{ guibg = 'x11 purple', guibg_hex = '#a020f0', guifb = 'Black' },
	{ guibg = 'x11purple', guibg_hex = '#a020f0', guifb = 'Black' },
	{ guibg = 'web purple', guibg_hex = '#800080', guifb = 'Black' },
	{ guibg = 'webpurple', guibg_hex = '#800080', guifb = 'Black' },
	{ guibg = 'medium purple', guibg_hex = '#9370db', guifb = 'Black' },
	{ guibg = 'mediumpurple', guibg_hex = '#9370db', guifb = 'Black' },
	{ guibg = 'thistle', guibg_hex = '#d8bfd8', guifb = 'Black' },
	{ guibg = 'snow1', guibg_hex = '#fffafa', guifb = 'Black' },
	{ guibg = 'snow2', guibg_hex = '#eee9e9', guifb = 'Black' },
	{ guibg = 'snow3', guibg_hex = '#cdc9c9', guifb = 'Black' },
	{ guibg = 'snow4', guibg_hex = '#8b8989', guifb = 'Black' },
	{ guibg = 'seashell1', guibg_hex = '#fff5ee', guifb = 'Black' },
	{ guibg = 'seashell2', guibg_hex = '#eee5de', guifb = 'Black' },
	{ guibg = 'seashell3', guibg_hex = '#cdc5bf', guifb = 'Black' },
	{ guibg = 'seashell4', guibg_hex = '#8b8682', guifb = 'Black' },
	{ guibg = 'antiquewhite1', guibg_hex = '#ffefdb', guifb = 'Black' },
	{ guibg = 'antiquewhite2', guibg_hex = '#eedfcc', guifb = 'Black' },
	{ guibg = 'antiquewhite3', guibg_hex = '#cdc0b0', guifb = 'Black' },
	{ guibg = 'antiquewhite4', guibg_hex = '#8b8378', guifb = 'Black' },
	{ guibg = 'bisque1', guibg_hex = '#ffe4c4', guifb = 'Black' },
	{ guibg = 'bisque2', guibg_hex = '#eed5b7', guifb = 'Black' },
	{ guibg = 'bisque3', guibg_hex = '#cdb79e', guifb = 'Black' },
	{ guibg = 'bisque4', guibg_hex = '#8b7d6b', guifb = 'Black' },
	{ guibg = 'peachpuff1', guibg_hex = '#ffdab9', guifb = 'Black' },
	{ guibg = 'peachpuff2', guibg_hex = '#eecbad', guifb = 'Black' },
	{ guibg = 'peachpuff3', guibg_hex = '#cdaf95', guifb = 'Black' },
	{ guibg = 'peachpuff4', guibg_hex = '#8b7765', guifb = 'Black' },
	{ guibg = 'navajowhite1', guibg_hex = '#ffdead', guifb = 'Black' },
	{ guibg = 'navajowhite2', guibg_hex = '#eecfa1', guifb = 'Black' },
	{ guibg = 'navajowhite3', guibg_hex = '#cdb38b', guifb = 'Black' },
	{ guibg = 'navajowhite4', guibg_hex = '#8b795e', guifb = 'Black' },
	{ guibg = 'lemonchiffon1', guibg_hex = '#fffacd', guifb = 'Black' },
	{ guibg = 'lemonchiffon2', guibg_hex = '#eee9bf', guifb = 'Black' },
	{ guibg = 'lemonchiffon3', guibg_hex = '#cdc9a5', guifb = 'Black' },
	{ guibg = 'lemonchiffon4', guibg_hex = '#8b8970', guifb = 'Black' },
	{ guibg = 'cornsilk1', guibg_hex = '#fff8dc', guifb = 'Black' },
	{ guibg = 'cornsilk2', guibg_hex = '#eee8cd', guifb = 'Black' },
	{ guibg = 'cornsilk3', guibg_hex = '#cdc8b1', guifb = 'Black' },
	{ guibg = 'cornsilk4', guibg_hex = '#8b8878', guifb = 'Black' },
	{ guibg = 'ivory1', guibg_hex = '#fffff0', guifb = 'Black' },
	{ guibg = 'ivory2', guibg_hex = '#eeeee0', guifb = 'Black' },
	{ guibg = 'ivory3', guibg_hex = '#cdcdc1', guifb = 'Black' },
	{ guibg = 'ivory4', guibg_hex = '#8b8b83', guifb = 'Black' },
	{ guibg = 'honeydew1', guibg_hex = '#f0fff0', guifb = 'Black' },
	{ guibg = 'honeydew2', guibg_hex = '#e0eee0', guifb = 'Black' },
	{ guibg = 'honeydew3', guibg_hex = '#c1cdc1', guifb = 'Black' },
	{ guibg = 'honeydew4', guibg_hex = '#838b83', guifb = 'Black' },
	{ guibg = 'lavenderblush1', guibg_hex = '#fff0f5', guifb = 'Black' },
	{ guibg = 'lavenderblush2', guibg_hex = '#eee0e5', guifb = 'Black' },
	{ guibg = 'lavenderblush3', guibg_hex = '#cdc1c5', guifb = 'Black' },
	{ guibg = 'lavenderblush4', guibg_hex = '#8b8386', guifb = 'Black' },
	{ guibg = 'mistyrose1', guibg_hex = '#ffe4e1', guifb = 'Black' },
	{ guibg = 'mistyrose2', guibg_hex = '#eed5d2', guifb = 'Black' },
	{ guibg = 'mistyrose3', guibg_hex = '#cdb7b5', guifb = 'Black' },
	{ guibg = 'mistyrose4', guibg_hex = '#8b7d7b', guifb = 'Black' },
	{ guibg = 'azure1', guibg_hex = '#f0ffff', guifb = 'Black' },
	{ guibg = 'azure2', guibg_hex = '#e0eeee', guifb = 'Black' },
	{ guibg = 'azure3', guibg_hex = '#c1cdcd', guifb = 'Black' },
	{ guibg = 'azure4', guibg_hex = '#838b8b', guifb = 'Black' },
	{ guibg = 'slateblue1', guibg_hex = '#836fff', guifb = 'Black' },
	{ guibg = 'slateblue2', guibg_hex = '#7a67ee', guifb = 'Black' },
	{ guibg = 'slateblue3', guibg_hex = '#6959cd', guifb = 'Black' },
	{ guibg = 'slateblue4', guibg_hex = '#473c8b', guifb = 'Black' },
	{ guibg = 'royalblue1', guibg_hex = '#4876ff', guifb = 'Black' },
	{ guibg = 'royalblue2', guibg_hex = '#436eee', guifb = 'Black' },
	{ guibg = 'royalblue3', guibg_hex = '#3a5fcd', guifb = 'Black' },
	{ guibg = 'royalblue4', guibg_hex = '#27408b', guifb = 'Black' },
	{ guibg = 'blue1', guibg_hex = '#0000ff', guifb = 'Black' },
	{ guibg = 'blue2', guibg_hex = '#0000ee', guifb = 'Black' },
	{ guibg = 'blue3', guibg_hex = '#0000cd', guifb = 'Black' },
	{ guibg = 'blue4', guibg_hex = '#00008b', guifb = 'Black' },
	{ guibg = 'dodgerblue1', guibg_hex = '#1e90ff', guifb = 'Black' },
	{ guibg = 'dodgerblue2', guibg_hex = '#1c86ee', guifb = 'Black' },
	{ guibg = 'dodgerblue3', guibg_hex = '#1874cd', guifb = 'Black' },
	{ guibg = 'dodgerblue4', guibg_hex = '#104e8b', guifb = 'Black' },
	{ guibg = 'steelblue1', guibg_hex = '#63b8ff', guifb = 'Black' },
	{ guibg = 'steelblue2', guibg_hex = '#5cacee', guifb = 'Black' },
	{ guibg = 'steelblue3', guibg_hex = '#4f94cd', guifb = 'Black' },
	{ guibg = 'steelblue4', guibg_hex = '#36648b', guifb = 'Black' },
	{ guibg = 'deepskyblue1', guibg_hex = '#00bfff', guifb = 'Black' },
	{ guibg = 'deepskyblue2', guibg_hex = '#00b2ee', guifb = 'Black' },
	{ guibg = 'deepskyblue3', guibg_hex = '#009acd', guifb = 'Black' },
	{ guibg = 'deepskyblue4', guibg_hex = '#00688b', guifb = 'Black' },
	{ guibg = 'skyblue1', guibg_hex = '#87ceff', guifb = 'Black' },
	{ guibg = 'skyblue2', guibg_hex = '#7ec0ee', guifb = 'Black' },
	{ guibg = 'skyblue3', guibg_hex = '#6ca6cd', guifb = 'Black' },
	{ guibg = 'skyblue4', guibg_hex = '#4a708b', guifb = 'Black' },
	{ guibg = 'lightskyblue1', guibg_hex = '#b0e2ff', guifb = 'Black' },
	{ guibg = 'lightskyblue2', guibg_hex = '#a4d3ee', guifb = 'Black' },
	{ guibg = 'lightskyblue3', guibg_hex = '#8db6cd', guifb = 'Black' },
	{ guibg = 'lightskyblue4', guibg_hex = '#607b8b', guifb = 'Black' },
	{ guibg = 'slategray1', guibg_hex = '#c6e2ff', guifb = 'Black' },
	{ guibg = 'slategray2', guibg_hex = '#b9d3ee', guifb = 'Black' },
	{ guibg = 'slategray3', guibg_hex = '#9fb6cd', guifb = 'Black' },
	{ guibg = 'slategray4', guibg_hex = '#6c7b8b', guifb = 'Black' },
	{ guibg = 'lightsteelblue1', guibg_hex = '#cae1ff', guifb = 'Black' },
	{ guibg = 'lightsteelblue2', guibg_hex = '#bcd2ee', guifb = 'Black' },
	{ guibg = 'lightsteelblue3', guibg_hex = '#a2b5cd', guifb = 'Black' },
	{ guibg = 'lightsteelblue4', guibg_hex = '#6e7b8b', guifb = 'Black' },
	{ guibg = 'lightblue1', guibg_hex = '#bfefff', guifb = 'Black' },
	{ guibg = 'lightblue2', guibg_hex = '#b2dfee', guifb = 'Black' },
	{ guibg = 'lightblue3', guibg_hex = '#9ac0cd', guifb = 'Black' },
	{ guibg = 'lightblue4', guibg_hex = '#68838b', guifb = 'Black' },
	{ guibg = 'lightcyan1', guibg_hex = '#e0ffff', guifb = 'Black' },
	{ guibg = 'lightcyan2', guibg_hex = '#d1eeee', guifb = 'Black' },
	{ guibg = 'lightcyan3', guibg_hex = '#b4cdcd', guifb = 'Black' },
	{ guibg = 'lightcyan4', guibg_hex = '#7a8b8b', guifb = 'Black' },
	{ guibg = 'paleturquoise1', guibg_hex = '#bbffff', guifb = 'Black' },
	{ guibg = 'paleturquoise2', guibg_hex = '#aeeeee', guifb = 'Black' },
	{ guibg = 'paleturquoise3', guibg_hex = '#96cdcd', guifb = 'Black' },
	{ guibg = 'paleturquoise4', guibg_hex = '#668b8b', guifb = 'Black' },
	{ guibg = 'cadetblue1', guibg_hex = '#98f5ff', guifb = 'Black' },
	{ guibg = 'cadetblue2', guibg_hex = '#8ee5ee', guifb = 'Black' },
	{ guibg = 'cadetblue3', guibg_hex = '#7ac5cd', guifb = 'Black' },
	{ guibg = 'cadetblue4', guibg_hex = '#53868b', guifb = 'Black' },
	{ guibg = 'turquoise1', guibg_hex = '#00f5ff', guifb = 'Black' },
	{ guibg = 'turquoise2', guibg_hex = '#00e5ee', guifb = 'Black' },
	{ guibg = 'turquoise3', guibg_hex = '#00c5cd', guifb = 'Black' },
	{ guibg = 'turquoise4', guibg_hex = '#00868b', guifb = 'Black' },
	{ guibg = 'cyan1', guibg_hex = '#00ffff', guifb = 'Black' },
	{ guibg = 'cyan2', guibg_hex = '#00eeee', guifb = 'Black' },
	{ guibg = 'cyan3', guibg_hex = '#00cdcd', guifb = 'Black' },
	{ guibg = 'cyan4', guibg_hex = '#008b8b', guifb = 'Black' },
	{ guibg = 'darkslategray1', guibg_hex = '#97ffff', guifb = 'Black' },
	{ guibg = 'darkslategray2', guibg_hex = '#8deeee', guifb = 'Black' },
	{ guibg = 'darkslategray3', guibg_hex = '#79cdcd', guifb = 'Black' },
	{ guibg = 'darkslategray4', guibg_hex = '#528b8b', guifb = 'Black' },
	{ guibg = 'aquamarine1', guibg_hex = '#7fffd4', guifb = 'Black' },
	{ guibg = 'aquamarine2', guibg_hex = '#76eec6', guifb = 'Black' },
	{ guibg = 'aquamarine3', guibg_hex = '#66cdaa', guifb = 'Black' },
	{ guibg = 'aquamarine4', guibg_hex = '#458b74', guifb = 'Black' },
	{ guibg = 'darkseagreen1', guibg_hex = '#c1ffc1', guifb = 'Black' },
	{ guibg = 'darkseagreen2', guibg_hex = '#b4eeb4', guifb = 'Black' },
	{ guibg = 'darkseagreen3', guibg_hex = '#9bcd9b', guifb = 'Black' },
	{ guibg = 'darkseagreen4', guibg_hex = '#698b69', guifb = 'Black' },
	{ guibg = 'seagreen1', guibg_hex = '#54ff9f', guifb = 'Black' },
	{ guibg = 'seagreen2', guibg_hex = '#4eee94', guifb = 'Black' },
	{ guibg = 'seagreen3', guibg_hex = '#43cd80', guifb = 'Black' },
	{ guibg = 'seagreen4', guibg_hex = '#2e8b57', guifb = 'Black' },
	{ guibg = 'palegreen1', guibg_hex = '#9aff9a', guifb = 'Black' },
	{ guibg = 'palegreen2', guibg_hex = '#90ee90', guifb = 'Black' },
	{ guibg = 'palegreen3', guibg_hex = '#7ccd7c', guifb = 'Black' },
	{ guibg = 'palegreen4', guibg_hex = '#548b54', guifb = 'Black' },
	{ guibg = 'springgreen1', guibg_hex = '#00ff7f', guifb = 'Black' },
	{ guibg = 'springgreen2', guibg_hex = '#00ee76', guifb = 'Black' },
	{ guibg = 'springgreen3', guibg_hex = '#00cd66', guifb = 'Black' },
	{ guibg = 'springgreen4', guibg_hex = '#008b45', guifb = 'Black' },
	{ guibg = 'green1', guibg_hex = '#00ff00', guifb = 'Black' },
	{ guibg = 'green2', guibg_hex = '#00ee00', guifb = 'Black' },
	{ guibg = 'green3', guibg_hex = '#00cd00', guifb = 'Black' },
	{ guibg = 'green4', guibg_hex = '#008b00', guifb = 'Black' },
	{ guibg = 'chartreuse1', guibg_hex = '#7fff00', guifb = 'Black' },
	{ guibg = 'chartreuse2', guibg_hex = '#76ee00', guifb = 'Black' },
	{ guibg = 'chartreuse3', guibg_hex = '#66cd00', guifb = 'Black' },
	{ guibg = 'chartreuse4', guibg_hex = '#458b00', guifb = 'Black' },
	{ guibg = 'olivedrab1', guibg_hex = '#c0ff3e', guifb = 'Black' },
	{ guibg = 'olivedrab2', guibg_hex = '#b3ee3a', guifb = 'Black' },
	{ guibg = 'olivedrab3', guibg_hex = '#9acd32', guifb = 'Black' },
	{ guibg = 'olivedrab4', guibg_hex = '#698b22', guifb = 'Black' },
	{ guibg = 'darkolivegreen1', guibg_hex = '#caff70', guifb = 'Black' },
	{ guibg = 'darkolivegreen2', guibg_hex = '#bcee68', guifb = 'Black' },
	{ guibg = 'darkolivegreen3', guibg_hex = '#a2cd5a', guifb = 'Black' },
	{ guibg = 'darkolivegreen4', guibg_hex = '#6e8b3d', guifb = 'Black' },
	{ guibg = 'khaki1', guibg_hex = '#fff68f', guifb = 'Black' },
	{ guibg = 'khaki2', guibg_hex = '#eee685', guifb = 'Black' },
	{ guibg = 'khaki3', guibg_hex = '#cdc673', guifb = 'Black' },
	{ guibg = 'khaki4', guibg_hex = '#8b864e', guifb = 'Black' },
	{ guibg = 'lightgoldenrod1', guibg_hex = '#ffec8b', guifb = 'Black' },
	{ guibg = 'lightgoldenrod2', guibg_hex = '#eedc82', guifb = 'Black' },
	{ guibg = 'lightgoldenrod3', guibg_hex = '#cdbe70', guifb = 'Black' },
	{ guibg = 'lightgoldenrod4', guibg_hex = '#8b814c', guifb = 'Black' },
	{ guibg = 'lightyellow1', guibg_hex = '#ffffe0', guifb = 'Black' },
	{ guibg = 'lightyellow2', guibg_hex = '#eeeed1', guifb = 'Black' },
	{ guibg = 'lightyellow3', guibg_hex = '#cdcdb4', guifb = 'Black' },
	{ guibg = 'lightyellow4', guibg_hex = '#8b8b7a', guifb = 'Black' },
	{ guibg = 'yellow1', guibg_hex = '#ffff00', guifb = 'Black' },
	{ guibg = 'yellow2', guibg_hex = '#eeee00', guifb = 'Black' },
	{ guibg = 'yellow3', guibg_hex = '#cdcd00', guifb = 'Black' },
	{ guibg = 'yellow4', guibg_hex = '#8b8b00', guifb = 'Black' },
	{ guibg = 'dark yellow', guibg_hex = '#8b8b00', guifb = 'Black' },
	{ guibg = 'darkyellow', guibg_hex = '#8b8b00', guifb = 'Black' },
	{ guibg = 'gold1', guibg_hex = '#ffd700', guifb = 'Black' },
	{ guibg = 'gold2', guibg_hex = '#eec900', guifb = 'Black' },
	{ guibg = 'gold3', guibg_hex = '#cdad00', guifb = 'Black' },
	{ guibg = 'gold4', guibg_hex = '#8b7500', guifb = 'Black' },
	{ guibg = 'goldenrod1', guibg_hex = '#ffc125', guifb = 'Black' },
	{ guibg = 'goldenrod2', guibg_hex = '#eeb422', guifb = 'Black' },
	{ guibg = 'goldenrod3', guibg_hex = '#cd9b1d', guifb = 'Black' },
	{ guibg = 'goldenrod4', guibg_hex = '#8b6914', guifb = 'Black' },
	{ guibg = 'darkgoldenrod1', guibg_hex = '#ffb90f', guifb = 'Black' },
	{ guibg = 'darkgoldenrod2', guibg_hex = '#eead0e', guifb = 'Black' },
	{ guibg = 'darkgoldenrod3', guibg_hex = '#cd950c', guifb = 'Black' },
	{ guibg = 'darkgoldenrod4', guibg_hex = '#8b6508', guifb = 'Black' },
	{ guibg = 'rosybrown1', guibg_hex = '#ffc1c1', guifb = 'Black' },
	{ guibg = 'rosybrown2', guibg_hex = '#eeb4b4', guifb = 'Black' },
	{ guibg = 'rosybrown3', guibg_hex = '#cd9b9b', guifb = 'Black' },
	{ guibg = 'rosybrown4', guibg_hex = '#8b6969', guifb = 'Black' },
	{ guibg = 'indianred1', guibg_hex = '#ff6a6a', guifb = 'Black' },
	{ guibg = 'indianred2', guibg_hex = '#ee6363', guifb = 'Black' },
	{ guibg = 'indianred3', guibg_hex = '#cd5555', guifb = 'Black' },
	{ guibg = 'indianred4', guibg_hex = '#8b3a3a', guifb = 'Black' },
	{ guibg = 'sienna1', guibg_hex = '#ff8247', guifb = 'Black' },
	{ guibg = 'sienna2', guibg_hex = '#ee7942', guifb = 'Black' },
	{ guibg = 'sienna3', guibg_hex = '#cd6839', guifb = 'Black' },
	{ guibg = 'sienna4', guibg_hex = '#8b4726', guifb = 'Black' },
	{ guibg = 'burlywood1', guibg_hex = '#ffd39b', guifb = 'Black' },
	{ guibg = 'burlywood2', guibg_hex = '#eec591', guifb = 'Black' },
	{ guibg = 'burlywood3', guibg_hex = '#cdaa7d', guifb = 'Black' },
	{ guibg = 'burlywood4', guibg_hex = '#8b7355', guifb = 'Black' },
	{ guibg = 'wheat1', guibg_hex = '#ffe7ba', guifb = 'Black' },
	{ guibg = 'wheat2', guibg_hex = '#eed8ae', guifb = 'Black' },
	{ guibg = 'wheat3', guibg_hex = '#cdba96', guifb = 'Black' },
	{ guibg = 'wheat4', guibg_hex = '#8b7e66', guifb = 'Black' },
	{ guibg = 'tan1', guibg_hex = '#ffa54f', guifb = 'Black' },
	{ guibg = 'tan2', guibg_hex = '#ee9a49', guifb = 'Black' },
	{ guibg = 'tan3', guibg_hex = '#cd853f', guifb = 'Black' },
	{ guibg = 'tan4', guibg_hex = '#8b5a2b', guifb = 'Black' },
	{ guibg = 'chocolate1', guibg_hex = '#ff7f24', guifb = 'Black' },
	{ guibg = 'chocolate2', guibg_hex = '#ee7621', guifb = 'Black' },
	{ guibg = 'chocolate3', guibg_hex = '#cd661d', guifb = 'Black' },
	{ guibg = 'chocolate4', guibg_hex = '#8b4513', guifb = 'Black' },
	{ guibg = 'firebrick1', guibg_hex = '#ff3030', guifb = 'Black' },
	{ guibg = 'firebrick2', guibg_hex = '#ee2c2c', guifb = 'Black' },
	{ guibg = 'firebrick3', guibg_hex = '#cd2626', guifb = 'Black' },
	{ guibg = 'firebrick4', guibg_hex = '#8b1a1a', guifb = 'Black' },
	{ guibg = 'brown1', guibg_hex = '#ff4040', guifb = 'Black' },
	{ guibg = 'brown2', guibg_hex = '#ee3b3b', guifb = 'Black' },
	{ guibg = 'brown3', guibg_hex = '#cd3333', guifb = 'Black' },
	{ guibg = 'brown4', guibg_hex = '#8b2323', guifb = 'Black' },
	{ guibg = 'salmon1', guibg_hex = '#ff8c69', guifb = 'Black' },
	{ guibg = 'salmon2', guibg_hex = '#ee8262', guifb = 'Black' },
	{ guibg = 'salmon3', guibg_hex = '#cd7054', guifb = 'Black' },
	{ guibg = 'salmon4', guibg_hex = '#8b4c39', guifb = 'Black' },
	{ guibg = 'lightsalmon1', guibg_hex = '#ffa07a', guifb = 'Black' },
	{ guibg = 'lightsalmon2', guibg_hex = '#ee9572', guifb = 'Black' },
	{ guibg = 'lightsalmon3', guibg_hex = '#cd8162', guifb = 'Black' },
	{ guibg = 'lightsalmon4', guibg_hex = '#8b5742', guifb = 'Black' },
	{ guibg = 'orange1', guibg_hex = '#ffa500', guifb = 'Black' },
	{ guibg = 'orange2', guibg_hex = '#ee9a00', guifb = 'Black' },
	{ guibg = 'orange3', guibg_hex = '#cd8500', guifb = 'Black' },
	{ guibg = 'orange4', guibg_hex = '#8b5a00', guifb = 'Black' },
	{ guibg = 'darkorange1', guibg_hex = '#ff7f00', guifb = 'Black' },
	{ guibg = 'darkorange2', guibg_hex = '#ee7600', guifb = 'Black' },
	{ guibg = 'darkorange3', guibg_hex = '#cd6600', guifb = 'Black' },
	{ guibg = 'darkorange4', guibg_hex = '#8b4500', guifb = 'Black' },
	{ guibg = 'coral1', guibg_hex = '#ff7256', guifb = 'Black' },
	{ guibg = 'coral2', guibg_hex = '#ee6a50', guifb = 'Black' },
	{ guibg = 'coral3', guibg_hex = '#cd5b45', guifb = 'Black' },
	{ guibg = 'coral4', guibg_hex = '#8b3e2f', guifb = 'Black' },
	{ guibg = 'tomato1', guibg_hex = '#ff6347', guifb = 'Black' },
	{ guibg = 'tomato2', guibg_hex = '#ee5c42', guifb = 'Black' },
	{ guibg = 'tomato3', guibg_hex = '#cd4f39', guifb = 'Black' },
	{ guibg = 'tomato4', guibg_hex = '#8b3626', guifb = 'Black' },
	{ guibg = 'orangered1', guibg_hex = '#ff4500', guifb = 'Black' },
	{ guibg = 'orangered2', guibg_hex = '#ee4000', guifb = 'Black' },
	{ guibg = 'orangered3', guibg_hex = '#cd3700', guifb = 'Black' },
	{ guibg = 'orangered4', guibg_hex = '#8b2500', guifb = 'Black' },
	{ guibg = 'light red', guibg_hex = '#ff8b8b', guifb = 'Black' },
	{ guibg = 'lightred', guibg_hex = '#ff8b8b', guifb = 'Black' },
	{ guibg = 'red1', guibg_hex = '#ff0000', guifb = 'Black' },
	{ guibg = 'red2', guibg_hex = '#ee0000', guifb = 'Black' },
	{ guibg = 'red3', guibg_hex = '#cd0000', guifb = 'Black' },
	{ guibg = 'red4', guibg_hex = '#8b0000', guifb = 'Black' },
	{ guibg = 'deeppink1', guibg_hex = '#ff1493', guifb = 'Black' },
	{ guibg = 'deeppink2', guibg_hex = '#ee1289', guifb = 'Black' },
	{ guibg = 'deeppink3', guibg_hex = '#cd1076', guifb = 'Black' },
	{ guibg = 'deeppink4', guibg_hex = '#8b0a50', guifb = 'Black' },
	{ guibg = 'hotpink1', guibg_hex = '#ff6eb4', guifb = 'Black' },
	{ guibg = 'hotpink2', guibg_hex = '#ee6aa7', guifb = 'Black' },
	{ guibg = 'hotpink3', guibg_hex = '#cd6090', guifb = 'Black' },
	{ guibg = 'hotpink4', guibg_hex = '#8b3a62', guifb = 'Black' },
	{ guibg = 'pink1', guibg_hex = '#ffb5c5', guifb = 'Black' },
	{ guibg = 'pink2', guibg_hex = '#eea9b8', guifb = 'Black' },
	{ guibg = 'pink3', guibg_hex = '#cd919e', guifb = 'Black' },
	{ guibg = 'pink4', guibg_hex = '#8b636c', guifb = 'Black' },
	{ guibg = 'lightpink1', guibg_hex = '#ffaeb9', guifb = 'Black' },
	{ guibg = 'lightpink2', guibg_hex = '#eea2ad', guifb = 'Black' },
	{ guibg = 'lightpink3', guibg_hex = '#cd8c95', guifb = 'Black' },
	{ guibg = 'lightpink4', guibg_hex = '#8b5f65', guifb = 'Black' },
	{ guibg = 'palevioletred1', guibg_hex = '#ff82ab', guifb = 'Black' },
	{ guibg = 'palevioletred2', guibg_hex = '#ee799f', guifb = 'Black' },
	{ guibg = 'palevioletred3', guibg_hex = '#cd6889', guifb = 'Black' },
	{ guibg = 'palevioletred4', guibg_hex = '#8b475d', guifb = 'Black' },
	{ guibg = 'maroon1', guibg_hex = '#ff34b3', guifb = 'Black' },
	{ guibg = 'maroon2', guibg_hex = '#ee30a7', guifb = 'Black' },
	{ guibg = 'maroon3', guibg_hex = '#cd2990', guifb = 'Black' },
	{ guibg = 'maroon4', guibg_hex = '#8b1c62', guifb = 'Black' },
	{ guibg = 'violetred1', guibg_hex = '#ff3e96', guifb = 'Black' },
	{ guibg = 'violetred2', guibg_hex = '#ee3a8c', guifb = 'Black' },
	{ guibg = 'violetred3', guibg_hex = '#cd3278', guifb = 'Black' },
	{ guibg = 'violetred4', guibg_hex = '#8b2252', guifb = 'Black' },
	{ guibg = 'light magenta', guibg_hex = '#ff8bff', guifb = 'Black' },
	{ guibg = 'lightmagenta', guibg_hex = '#ff8bff', guifb = 'Black' },
	{ guibg = 'magenta1', guibg_hex = '#ff00ff', guifb = 'Black' },
	{ guibg = 'magenta2', guibg_hex = '#ee00ee', guifb = 'Black' },
	{ guibg = 'magenta3', guibg_hex = '#cd00cd', guifb = 'Black' },
	{ guibg = 'magenta4', guibg_hex = '#8b008b', guifb = 'Black' },
	{ guibg = 'orchid1', guibg_hex = '#ff83fa', guifb = 'Black' },
	{ guibg = 'orchid2', guibg_hex = '#ee7ae9', guifb = 'Black' },
	{ guibg = 'orchid3', guibg_hex = '#cd69c9', guifb = 'Black' },
	{ guibg = 'orchid4', guibg_hex = '#8b4789', guifb = 'Black' },
	{ guibg = 'plum1', guibg_hex = '#ffbbff', guifb = 'Black' },
	{ guibg = 'plum2', guibg_hex = '#eeaeee', guifb = 'Black' },
	{ guibg = 'plum3', guibg_hex = '#cd96cd', guifb = 'Black' },
	{ guibg = 'plum4', guibg_hex = '#8b668b', guifb = 'Black' },
	{ guibg = 'mediumorchid1', guibg_hex = '#e066ff', guifb = 'Black' },
	{ guibg = 'mediumorchid2', guibg_hex = '#d15fee', guifb = 'Black' },
	{ guibg = 'mediumorchid3', guibg_hex = '#b452cd', guifb = 'Black' },
	{ guibg = 'mediumorchid4', guibg_hex = '#7a378b', guifb = 'Black' },
	{ guibg = 'darkorchid1', guibg_hex = '#bf3eff', guifb = 'Black' },
	{ guibg = 'darkorchid2', guibg_hex = '#b23aee', guifb = 'Black' },
	{ guibg = 'darkorchid3', guibg_hex = '#9a32cd', guifb = 'Black' },
	{ guibg = 'darkorchid4', guibg_hex = '#68228b', guifb = 'Black' },
	{ guibg = 'purple1', guibg_hex = '#9b30ff', guifb = 'Black' },
	{ guibg = 'purple2', guibg_hex = '#912cee', guifb = 'Black' },
	{ guibg = 'purple3', guibg_hex = '#7d26cd', guifb = 'Black' },
	{ guibg = 'purple4', guibg_hex = '#551a8b', guifb = 'Black' },
	{ guibg = 'mediumpurple1', guibg_hex = '#ab82ff', guifb = 'Black' },
	{ guibg = 'mediumpurple2', guibg_hex = '#9f79ee', guifb = 'Black' },
	{ guibg = 'mediumpurple3', guibg_hex = '#8968cd', guifb = 'Black' },
	{ guibg = 'mediumpurple4', guibg_hex = '#5d478b', guifb = 'Black' },
	{ guibg = 'thistle1', guibg_hex = '#ffe1ff', guifb = 'Black' },
	{ guibg = 'thistle2', guibg_hex = '#eed2ee', guifb = 'Black' },
	{ guibg = 'thistle3', guibg_hex = '#cdb5cd', guifb = 'Black' },
	{ guibg = 'thistle4', guibg_hex = '#8b7b8b', guifb = 'Black' },
	{ guibg = 'gray0', guibg_hex = '#000000', guifb = 'Black' },
	{ guibg = 'grey0', guibg_hex = '#000000', guifb = 'Black' },
	{ guibg = 'gray1', guibg_hex = '#030303', guifb = 'Black' },
	{ guibg = 'grey1', guibg_hex = '#030303', guifb = 'Black' },
	{ guibg = 'gray2', guibg_hex = '#050505', guifb = 'Black' },
	{ guibg = 'grey2', guibg_hex = '#050505', guifb = 'Black' },
	{ guibg = 'gray3', guibg_hex = '#080808', guifb = 'Black' },
	{ guibg = 'grey3', guibg_hex = '#080808', guifb = 'Black' },
	{ guibg = 'gray4', guibg_hex = '#0a0a0a', guifb = 'Black' },
	{ guibg = 'grey4', guibg_hex = '#0a0a0a', guifb = 'Black' },
	{ guibg = 'gray5', guibg_hex = '#0d0d0d', guifb = 'Black' },
	{ guibg = 'grey5', guibg_hex = '#0d0d0d', guifb = 'Black' },
	{ guibg = 'gray6', guibg_hex = '#0f0f0f', guifb = 'Black' },
	{ guibg = 'grey6', guibg_hex = '#0f0f0f', guifb = 'Black' },
	{ guibg = 'gray7', guibg_hex = '#121212', guifb = 'Black' },
	{ guibg = 'grey7', guibg_hex = '#121212', guifb = 'Black' },
	{ guibg = 'gray8', guibg_hex = '#141414', guifb = 'Black' },
	{ guibg = 'grey8', guibg_hex = '#141414', guifb = 'Black' },
	{ guibg = 'gray9', guibg_hex = '#171717', guifb = 'Black' },
	{ guibg = 'grey9', guibg_hex = '#171717', guifb = 'Black' },
	{ guibg = 'gray10', guibg_hex = '#1a1a1a', guifb = 'Black' },
	{ guibg = 'grey10', guibg_hex = '#1a1a1a', guifb = 'Black' },
	{ guibg = 'gray11', guibg_hex = '#1c1c1c', guifb = 'Black' },
	{ guibg = 'grey11', guibg_hex = '#1c1c1c', guifb = 'Black' },
	{ guibg = 'gray12', guibg_hex = '#1f1f1f', guifb = 'Black' },
	{ guibg = 'grey12', guibg_hex = '#1f1f1f', guifb = 'Black' },
	{ guibg = 'gray13', guibg_hex = '#212121', guifb = 'Black' },
	{ guibg = 'grey13', guibg_hex = '#212121', guifb = 'Black' },
	{ guibg = 'gray14', guibg_hex = '#242424', guifb = 'Black' },
	{ guibg = 'grey14', guibg_hex = '#242424', guifb = 'Black' },
	{ guibg = 'gray15', guibg_hex = '#262626', guifb = 'Black' },
	{ guibg = 'grey15', guibg_hex = '#262626', guifb = 'Black' },
	{ guibg = 'gray16', guibg_hex = '#292929', guifb = 'Black' },
	{ guibg = 'grey16', guibg_hex = '#292929', guifb = 'Black' },
	{ guibg = 'gray17', guibg_hex = '#2b2b2b', guifb = 'Black' },
	{ guibg = 'grey17', guibg_hex = '#2b2b2b', guifb = 'Black' },
	{ guibg = 'gray18', guibg_hex = '#2e2e2e', guifb = 'Black' },
	{ guibg = 'grey18', guibg_hex = '#2e2e2e', guifb = 'Black' },
	{ guibg = 'gray19', guibg_hex = '#303030', guifb = 'Black' },
	{ guibg = 'grey19', guibg_hex = '#303030', guifb = 'Black' },
	{ guibg = 'gray20', guibg_hex = '#333333', guifb = 'Black' },
	{ guibg = 'grey20', guibg_hex = '#333333', guifb = 'Black' },
	{ guibg = 'gray21', guibg_hex = '#363636', guifb = 'Black' },
	{ guibg = 'grey21', guibg_hex = '#363636', guifb = 'Black' },
	{ guibg = 'gray22', guibg_hex = '#383838', guifb = 'Black' },
	{ guibg = 'grey22', guibg_hex = '#383838', guifb = 'Black' },
	{ guibg = 'gray23', guibg_hex = '#3b3b3b', guifb = 'Black' },
	{ guibg = 'grey23', guibg_hex = '#3b3b3b', guifb = 'Black' },
	{ guibg = 'gray24', guibg_hex = '#3d3d3d', guifb = 'Black' },
	{ guibg = 'grey24', guibg_hex = '#3d3d3d', guifb = 'Black' },
	{ guibg = 'gray25', guibg_hex = '#404040', guifb = 'Black' },
	{ guibg = 'grey25', guibg_hex = '#404040', guifb = 'Black' },
	{ guibg = 'gray26', guibg_hex = '#424242', guifb = 'Black' },
	{ guibg = 'grey26', guibg_hex = '#424242', guifb = 'Black' },
	{ guibg = 'gray27', guibg_hex = '#454545', guifb = 'Black' },
	{ guibg = 'grey27', guibg_hex = '#454545', guifb = 'Black' },
	{ guibg = 'gray28', guibg_hex = '#474747', guifb = 'Black' },
	{ guibg = 'grey28', guibg_hex = '#474747', guifb = 'Black' },
	{ guibg = 'gray29', guibg_hex = '#4a4a4a', guifb = 'Black' },
	{ guibg = 'grey29', guibg_hex = '#4a4a4a', guifb = 'Black' },
	{ guibg = 'gray30', guibg_hex = '#4d4d4d', guifb = 'Black' },
	{ guibg = 'grey30', guibg_hex = '#4d4d4d', guifb = 'Black' },
	{ guibg = 'gray31', guibg_hex = '#4f4f4f', guifb = 'Black' },
	{ guibg = 'grey31', guibg_hex = '#4f4f4f', guifb = 'Black' },
	{ guibg = 'gray32', guibg_hex = '#525252', guifb = 'Black' },
	{ guibg = 'grey32', guibg_hex = '#525252', guifb = 'Black' },
	{ guibg = 'gray33', guibg_hex = '#545454', guifb = 'Black' },
	{ guibg = 'grey33', guibg_hex = '#545454', guifb = 'Black' },
	{ guibg = 'gray34', guibg_hex = '#575757', guifb = 'Black' },
	{ guibg = 'grey34', guibg_hex = '#575757', guifb = 'Black' },
	{ guibg = 'gray35', guibg_hex = '#595959', guifb = 'Black' },
	{ guibg = 'grey35', guibg_hex = '#595959', guifb = 'Black' },
	{ guibg = 'gray36', guibg_hex = '#5c5c5c', guifb = 'Black' },
	{ guibg = 'grey36', guibg_hex = '#5c5c5c', guifb = 'Black' },
	{ guibg = 'gray37', guibg_hex = '#5e5e5e', guifb = 'Black' },
	{ guibg = 'grey37', guibg_hex = '#5e5e5e', guifb = 'Black' },
	{ guibg = 'gray38', guibg_hex = '#616161', guifb = 'Black' },
	{ guibg = 'grey38', guibg_hex = '#616161', guifb = 'Black' },
	{ guibg = 'gray39', guibg_hex = '#636363', guifb = 'Black' },
	{ guibg = 'grey39', guibg_hex = '#636363', guifb = 'Black' },
	{ guibg = 'gray40', guibg_hex = '#666666', guifb = 'Black' },
	{ guibg = 'grey40', guibg_hex = '#666666', guifb = 'Black' },
	{ guibg = 'gray41', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'grey41', guibg_hex = '#696969', guifb = 'Black' },
	{ guibg = 'gray42', guibg_hex = '#6b6b6b', guifb = 'Black' },
	{ guibg = 'grey42', guibg_hex = '#6b6b6b', guifb = 'Black' },
	{ guibg = 'gray43', guibg_hex = '#6e6e6e', guifb = 'Black' },
	{ guibg = 'grey43', guibg_hex = '#6e6e6e', guifb = 'Black' },
	{ guibg = 'gray44', guibg_hex = '#707070', guifb = 'Black' },
	{ guibg = 'grey44', guibg_hex = '#707070', guifb = 'Black' },
	{ guibg = 'gray45', guibg_hex = '#737373', guifb = 'Black' },
	{ guibg = 'grey45', guibg_hex = '#737373', guifb = 'Black' },
	{ guibg = 'gray46', guibg_hex = '#757575', guifb = 'Black' },
	{ guibg = 'grey46', guibg_hex = '#757575', guifb = 'Black' },
	{ guibg = 'gray47', guibg_hex = '#787878', guifb = 'Black' },
	{ guibg = 'grey47', guibg_hex = '#787878', guifb = 'Black' },
	{ guibg = 'gray48', guibg_hex = '#7a7a7a', guifb = 'Black' },
	{ guibg = 'grey48', guibg_hex = '#7a7a7a', guifb = 'Black' },
	{ guibg = 'gray49', guibg_hex = '#7d7d7d', guifb = 'Black' },
	{ guibg = 'grey49', guibg_hex = '#7d7d7d', guifb = 'Black' },
	{ guibg = 'gray50', guibg_hex = '#7f7f7f', guifb = 'Black' },
	{ guibg = 'grey50', guibg_hex = '#7f7f7f', guifb = 'Black' },
	{ guibg = 'gray51', guibg_hex = '#828282', guifb = 'Black' },
	{ guibg = 'grey51', guibg_hex = '#828282', guifb = 'Black' },
	{ guibg = 'gray52', guibg_hex = '#858585', guifb = 'Black' },
	{ guibg = 'grey52', guibg_hex = '#858585', guifb = 'Black' },
	{ guibg = 'gray53', guibg_hex = '#878787', guifb = 'Black' },
	{ guibg = 'grey53', guibg_hex = '#878787', guifb = 'Black' },
	{ guibg = 'gray54', guibg_hex = '#8a8a8a', guifb = 'Black' },
	{ guibg = 'grey54', guibg_hex = '#8a8a8a', guifb = 'Black' },
	{ guibg = 'gray55', guibg_hex = '#8c8c8c', guifb = 'Black' },
	{ guibg = 'grey55', guibg_hex = '#8c8c8c', guifb = 'Black' },
	{ guibg = 'gray56', guibg_hex = '#8f8f8f', guifb = 'Black' },
	{ guibg = 'grey56', guibg_hex = '#8f8f8f', guifb = 'Black' },
	{ guibg = 'gray57', guibg_hex = '#919191', guifb = 'Black' },
	{ guibg = 'grey57', guibg_hex = '#919191', guifb = 'Black' },
	{ guibg = 'gray58', guibg_hex = '#949494', guifb = 'Black' },
	{ guibg = 'grey58', guibg_hex = '#949494', guifb = 'Black' },
	{ guibg = 'gray59', guibg_hex = '#969696', guifb = 'Black' },
	{ guibg = 'grey59', guibg_hex = '#969696', guifb = 'Black' },
	{ guibg = 'gray60', guibg_hex = '#999999', guifb = 'Black' },
	{ guibg = 'grey60', guibg_hex = '#999999', guifb = 'Black' },
	{ guibg = 'gray61', guibg_hex = '#9c9c9c', guifb = 'Black' },
	{ guibg = 'grey61', guibg_hex = '#9c9c9c', guifb = 'Black' },
	{ guibg = 'gray62', guibg_hex = '#9e9e9e', guifb = 'Black' },
	{ guibg = 'grey62', guibg_hex = '#9e9e9e', guifb = 'Black' },
	{ guibg = 'gray63', guibg_hex = '#a1a1a1', guifb = 'Black' },
	{ guibg = 'grey63', guibg_hex = '#a1a1a1', guifb = 'Black' },
	{ guibg = 'gray64', guibg_hex = '#a3a3a3', guifb = 'Black' },
	{ guibg = 'grey64', guibg_hex = '#a3a3a3', guifb = 'Black' },
	{ guibg = 'gray65', guibg_hex = '#a6a6a6', guifb = 'Black' },
	{ guibg = 'grey65', guibg_hex = '#a6a6a6', guifb = 'Black' },
	{ guibg = 'gray66', guibg_hex = '#a8a8a8', guifb = 'Black' },
	{ guibg = 'grey66', guibg_hex = '#a8a8a8', guifb = 'Black' },
	{ guibg = 'gray67', guibg_hex = '#ababab', guifb = 'Black' },
	{ guibg = 'grey67', guibg_hex = '#ababab', guifb = 'Black' },
	{ guibg = 'gray68', guibg_hex = '#adadad', guifb = 'Black' },
	{ guibg = 'grey68', guibg_hex = '#adadad', guifb = 'Black' },
	{ guibg = 'gray69', guibg_hex = '#b0b0b0', guifb = 'Black' },
	{ guibg = 'grey69', guibg_hex = '#b0b0b0', guifb = 'Black' },
	{ guibg = 'gray70', guibg_hex = '#b3b3b3', guifb = 'Black' },
	{ guibg = 'grey70', guibg_hex = '#b3b3b3', guifb = 'Black' },
	{ guibg = 'gray71', guibg_hex = '#b5b5b5', guifb = 'Black' },
	{ guibg = 'grey71', guibg_hex = '#b5b5b5', guifb = 'Black' },
	{ guibg = 'gray72', guibg_hex = '#b8b8b8', guifb = 'Black' },
	{ guibg = 'grey72', guibg_hex = '#b8b8b8', guifb = 'Black' },
	{ guibg = 'gray73', guibg_hex = '#bababa', guifb = 'Black' },
	{ guibg = 'grey73', guibg_hex = '#bababa', guifb = 'Black' },
	{ guibg = 'gray74', guibg_hex = '#bdbdbd', guifb = 'Black' },
	{ guibg = 'grey74', guibg_hex = '#bdbdbd', guifb = 'Black' },
	{ guibg = 'gray75', guibg_hex = '#bfbfbf', guifb = 'Black' },
	{ guibg = 'grey75', guibg_hex = '#bfbfbf', guifb = 'Black' },
	{ guibg = 'gray76', guibg_hex = '#c2c2c2', guifb = 'Black' },
	{ guibg = 'grey76', guibg_hex = '#c2c2c2', guifb = 'Black' },
	{ guibg = 'gray77', guibg_hex = '#c4c4c4', guifb = 'Black' },
	{ guibg = 'grey77', guibg_hex = '#c4c4c4', guifb = 'Black' },
	{ guibg = 'gray78', guibg_hex = '#c7c7c7', guifb = 'Black' },
	{ guibg = 'grey78', guibg_hex = '#c7c7c7', guifb = 'Black' },
	{ guibg = 'gray79', guibg_hex = '#c9c9c9', guifb = 'Black' },
	{ guibg = 'grey79', guibg_hex = '#c9c9c9', guifb = 'Black' },
	{ guibg = 'gray80', guibg_hex = '#cccccc', guifb = 'Black' },
	{ guibg = 'grey80', guibg_hex = '#cccccc', guifb = 'Black' },
	{ guibg = 'gray81', guibg_hex = '#cfcfcf', guifb = 'Black' },
	{ guibg = 'grey81', guibg_hex = '#cfcfcf', guifb = 'Black' },
	{ guibg = 'gray82', guibg_hex = '#d1d1d1', guifb = 'Black' },
	{ guibg = 'grey82', guibg_hex = '#d1d1d1', guifb = 'Black' },
	{ guibg = 'gray83', guibg_hex = '#d4d4d4', guifb = 'Black' },
	{ guibg = 'grey83', guibg_hex = '#d4d4d4', guifb = 'Black' },
	{ guibg = 'gray84', guibg_hex = '#d6d6d6', guifb = 'Black' },
	{ guibg = 'grey84', guibg_hex = '#d6d6d6', guifb = 'Black' },
	{ guibg = 'gray85', guibg_hex = '#d9d9d9', guifb = 'Black' },
	{ guibg = 'grey85', guibg_hex = '#d9d9d9', guifb = 'Black' },
	{ guibg = 'gray86', guibg_hex = '#dbdbdb', guifb = 'Black' },
	{ guibg = 'grey86', guibg_hex = '#dbdbdb', guifb = 'Black' },
	{ guibg = 'gray87', guibg_hex = '#dedede', guifb = 'Black' },
	{ guibg = 'grey87', guibg_hex = '#dedede', guifb = 'Black' },
	{ guibg = 'gray88', guibg_hex = '#e0e0e0', guifb = 'Black' },
	{ guibg = 'grey88', guibg_hex = '#e0e0e0', guifb = 'Black' },
	{ guibg = 'gray89', guibg_hex = '#e3e3e3', guifb = 'Black' },
	{ guibg = 'grey89', guibg_hex = '#e3e3e3', guifb = 'Black' },
	{ guibg = 'gray90', guibg_hex = '#e5e5e5', guifb = 'Black' },
	{ guibg = 'grey90', guibg_hex = '#e5e5e5', guifb = 'Black' },
	{ guibg = 'gray91', guibg_hex = '#e8e8e8', guifb = 'Black' },
	{ guibg = 'grey91', guibg_hex = '#e8e8e8', guifb = 'Black' },
	{ guibg = 'gray92', guibg_hex = '#ebebeb', guifb = 'Black' },
	{ guibg = 'grey92', guibg_hex = '#ebebeb', guifb = 'Black' },
	{ guibg = 'gray93', guibg_hex = '#ededed', guifb = 'Black' },
	{ guibg = 'grey93', guibg_hex = '#ededed', guifb = 'Black' },
	{ guibg = 'gray94', guibg_hex = '#f0f0f0', guifb = 'Black' },
	{ guibg = 'grey94', guibg_hex = '#f0f0f0', guifb = 'Black' },
	{ guibg = 'gray95', guibg_hex = '#f2f2f2', guifb = 'Black' },
	{ guibg = 'grey95', guibg_hex = '#f2f2f2', guifb = 'Black' },
	{ guibg = 'gray96', guibg_hex = '#f5f5f5', guifb = 'Black' },
	{ guibg = 'grey96', guibg_hex = '#f5f5f5', guifb = 'Black' },
	{ guibg = 'gray97', guibg_hex = '#f7f7f7', guifb = 'Black' },
	{ guibg = 'grey97', guibg_hex = '#f7f7f7', guifb = 'Black' },
	{ guibg = 'gray98', guibg_hex = '#fafafa', guifb = 'Black' },
	{ guibg = 'grey98', guibg_hex = '#fafafa', guifb = 'Black' },
	{ guibg = 'gray99', guibg_hex = '#fcfcfc', guifb = 'Black' },
	{ guibg = 'grey99', guibg_hex = '#fcfcfc', guifb = 'Black' },
	{ guibg = 'gray100', guibg_hex = '#ffffff', guifb = 'Black' },
	{ guibg = 'grey100', guibg_hex = '#ffffff', guifb = 'Black' },
	{ guibg = 'dark grey', guibg_hex = '#a9a9a9', guifb = 'Black' },
	{ guibg = 'darkgrey', guibg_hex = '#a9a9a9', guifb = 'Black' },
	{ guibg = 'dark gray', guibg_hex = '#a9a9a9', guifb = 'Black' },
	{ guibg = 'darkgray', guibg_hex = '#a9a9a9', guifb = 'Black' },
	{ guibg = 'dark blue', guibg_hex = '#00008b', guifb = 'Black' },
	{ guibg = 'darkblue', guibg_hex = '#00008b', guifb = 'Black' },
	{ guibg = 'dark cyan', guibg_hex = '#008b8b', guifb = 'Black' },
	{ guibg = 'darkcyan', guibg_hex = '#008b8b', guifb = 'Black' },
	{ guibg = 'dark magenta', guibg_hex = '#8b008b', guifb = 'Black' },
	{ guibg = 'darkmagenta', guibg_hex = '#8b008b', guifb = 'Black' },
	{ guibg = 'dark red', guibg_hex = '#8b0000', guifb = 'Black' },
	{ guibg = 'darkred', guibg_hex = '#8b0000', guifb = 'Black' },
	{ guibg = 'light green', guibg_hex = '#90ee90', guifb = 'Black' },
	{ guibg = 'lightgreen', guibg_hex = '#90ee90', guifb = 'Black' },
	{ guibg = 'crimson', guibg_hex = '#dc143c', guifb = 'Black' },
	{ guibg = 'indigo', guibg_hex = '#4b0082', guifb = 'Black' },
	{ guibg = 'olive', guibg_hex = '#808000', guifb = 'Black' },
	{ guibg = 'rebecca purple', guibg_hex = '#663399', guifb = 'Black' },
	{ guibg = 'rebeccapurple', guibg_hex = '#663399', guifb = 'Black' },
	{ guibg = 'silver', guibg_hex = '#c0c0c0', guifb = 'Black' },
	{ guibg = 'teal', guibg_hex = '#008080', guifb = 'Black' },
}

print(colour_maps[math.random(1, #colour_maps)].guibg)
